import java.util.InputMismatchException;
import java.util.Scanner;

public class UI {

    public void intro() throws InterruptedException {

        System.out.println("\nWelcome to BattleShips\n\n");
        Thread.sleep(2000);
    }


    public void gameMode() {

        System.out.println("-> to play PVP, press 1");
        System.out.println("-> To play against AI, press 2");
        System.out.print("\n== Currently PVP is unavailable ==\n\n");

        int userInput;
        boolean isNumber = false;
        while (!isNumber) {

            System.out.print("Please enter mode: ");
            Scanner scanNumber = new Scanner(System.in);
            try {
                userInput = scanNumber.nextInt();
            } catch(InputMismatchException ar) {
                continue;
            }
            if ((userInput == 2)) {
                isNumber = true;
            }
        }
    }

    public int placeYourShips() {

        System.out.println("\n\n-> to place ships, press 1");
        System.out.println("-> to use autogenerated ships, press 2\n\n");

        int userInput;
        boolean isNumber = false;
        while (true) {

            System.out.print("Please enter your choice: ");
            Scanner scanNumber = new Scanner(System.in);
            try {
                userInput = scanNumber.nextInt();
            } catch(InputMismatchException ar) {
                continue;
            }
            if ((userInput == 1 || userInput == 2)) {
                return userInput;
            }
        }

    }
}
